[versions]
reactorCore = "3.5.5-SNAPSHOT"
reactorAddons = "3.5.2-SNAPSHOT"
# Other shared versions
kotlin = "1.7.0"

[libraries]
reactor-core = { module = "io.projectreactor:reactor-core", version.ref = "reactorCore" }
reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "reactorCore" }
reactor-adapter = { module = "io.projectreactor.addons:reactor-adapter", version.ref = "reactorAddons" }
reactor-extra = { module = "io.projectreactor.addons:reactor-extra", version.ref = "reactorAddons" }
assertj = "org.assertj:assertj-core:3.25.3"
jsr305 = "com.google.code.findbugs:jsr305:3.0.1"
junit4 = "junit:junit:4.13.2"
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
rxJava2 = "io.reactivex.rxjava2:rxjava:2.2.21"

[plugins]
artifactory = { id = "com.jfrog.artifactory", version = "4.27.1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-dokka = { id = "org.jetbrains.dokka", version = "1.7.0" }
